### ISSUE TITLE
Working `<C-S-?>` implementation 

### ISSUE THREAD

**Issue by tigh-latte** [jonathancyu/dotfiles#1]
Hey! :wave:

Hope you don't mind me raising an issue here but couldn't think of a better way to get in touch.

I've spent a part of this evening getting `<C-S-?>` working in neovim on my alacritty+tmux setup, and in doing so I was searching Github to find other people's configs to see if it had been already solved, and, in doing so I stumbled onto your repo due to [this TODO](https://github.com/jonathancyu/dotfiles/blob/f765da5256c7537afe0636e826a9be9d709786c6/.config/alacritty/alacritty.toml#L27-L30). I'm guessing we both found the same out-of-date reddit post lmao.

Anyway, a wee while later, I got everything working and figured I'd point you in the right direction. After a bit of digging through alacritty's issues, I found [this](https://github.com/alacritty/alacritty/issues/7892#issuecomment-2040525690) and [this](https://github.com/alacritty/alacritty/issues/2688#issuecomment-516613134).

So, the correct way to do enable ctrl+shift handling is:
```
[[keyboard.bindings]]
  key   = "A"
  mods  = "Control | Shift"
  chars = "\u001b[65;6u"
```

Here's the [full config](https://github.com/tigh-latte/dotfiles/blob/c3943dc893cb58031c91aeb037f10e8ee78cfbe4/.config/alacritty/keyboard.toml) if you'd like.

**Comment by jonathancyu** [comment]
Oh awesome, thank you so much!
I actually decided not to follow through with this implementation because of annoying behavior in neovim - if there's nothing bound it'll type out the control sequence characters which was pretty annoying.
Now that I think about it, I just need to bind them to nop in insert mode... Thanks for the tip!

**Comment by jonathancyu** [comment]
fixed in commit [this commit](https://github.com/jonathancyu/dotfiles/commit/24a0d2390b64867c6843c3572af8f279e12f51c1), thank you!
